language: cpp
compiler: gcc
dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  - sudo apt-get install -qq g++-7 cmake
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  - wget -q https://dl.bintray.com/boostorg/release/1.65.1/source/boost_1_65_1.tar.gz
  - tar xfz boost_1_65_1.tar.gz && cd boost_1_65_1
  - ./bootstrap.sh && sudo ./b2 -d0 --with-libraries=program_options,filesystem,system -j 2 link=static runtime-link=shared install
  - sudo ldconfig
  - cd ..

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j 2 && ./test/unit_tests
