sudo: required

services:
  - docker

before_install:
  - travis_wait docker pull viyadb/devenv:latest

script:
  - docker run --rm -v $(pwd):/v viyadb/devenv:latest /bin/bash -c 'mkdir /v/build; cd /v/build; cmake ..; make -j8 && ./test/unit_tests; exit $?'
